import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import Header from "../Commponnent/Header";
import Footer from "../Commponnent/Footer";
import { MovieContextProvider } from "@/contextAPI/ContextAPI/MovieContext";
import { TVContextProvider } from "@/contextAPI/ContextAPI/TvContext";
import { TrendingContextProvider } from "@/contextAPI/ContextAPI/TrendingContext";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MovieContextProvider>
      <TVContextProvider>
        {/* <TrendingContextProvider> */}
          <html lang="en">
            <body className={inter.className}>
              <Header />
              {children}
              <Footer />
            </body>
          </html>
        {/* </TrendingContextProvider> */}
      </TVContextProvider>
    </MovieContextProvider>

  );
}
