import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import Header from "../Commponnent/Header";
import Footer from "../Commponnent/Footer";
import UptoPAge from "@/Commponnent/UptoPAge";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
          <html lang="en">
            <body className={inter.className}>
              <Header />
              {children}
              <UptoPAge/>
              <Footer />
            </body>
          </html>
        
     

  );
}
